name: Dev Container CI
on:
  push:
    paths:
      - '.devcontainer/**'
      - 'tests/**'
      - 'main.py'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v4

      - name: Dev Container のビルド＆テスト
        uses: devcontainers/ci@v0.2
        with:
          runCmd: pytest -q

